# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClickMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClickMe
  pod 'SwiftyJSON', '~> 4.0'
  pod 'CustomIOSAlertView', '~> 0.9.5'
  pod 'SideMenu'

end
